name: Dependency Review
on:
  pull_request:
    branches: [main]
permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dep-review:
    uses: greenticai/.github/.github/workflows/dependency-review.yml@main
    secrets: inherit
